### ISSUE TITLE
Title Name issue

### ISSUE THREAD

**Issue by HammadMaqbool** [AzkarUlHassan/cpp-practice-programs#2]
In the program [722bf81](https://github.com/AzkarUlHassan/cpp-practice-programs/commit/722bf81c8da47f4226e63df35abafb1005948cd0) you are using two time .. before cpp please fix this issue.

**Comment by AzkarUlHassan** [comment]
issue #2 fixes the commit [d00bf98](https://github.com/AzkarUlHassan/cpp-practice-programs/commit/d00bf985b8481f10a030c663bae013b998bee058)
